In [2]:
import tensorflow as tf
import os
#os.environ["CUDA_VISIBLE_DEVICES"]="-1"  #disables GPU 
import matplotlib.pyplot as plt
import numpy as np
tf.__version__

'2.6.0'

In [3]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 9324586445791826570
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 6469084774
locality {
  bus_id: 1
  links {
  }
}
incarnation: 9460460611578404085
physical_device_desc: "device: 0, name: NVIDIA GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1"
]


In [4]:
from tensorflow.keras.applications import VGG16

conv_base = VGG16(weights='imagenet',
                  include_top=False,
                  input_shape=(224, 224, 3))



In [26]:
import os
import cv2
import numpy as np

def load_data (data_path,img_shape,prefix):

    img_rows=img_shape[0]
    img_cols=img_shape[1]
    num_channel=img_shape[2]

    labels=[]
    data=[]
    len_list_img=0
    num_class=0

    img_list=os.listdir(data_path)    
    for img in img_list:
        input_img=cv2.imread(data_path + '/'+ img )
        input_img=cv2.resize(input_img,(img_rows,img_cols))
        input_img = tf.keras.applications.vgg16.preprocess_input(input_img, data_format=None)
        data.append(input_img)
        index = int(img.replace(prefix, '').replace('-', '').replace('.jpg', ''))
        labels.append(index)
           
    data = np.array(data)
    data = data.astype('float32')
    data /= 255
    labels=np.array(labels)
    print('data shape',data.shape)
    print('labels shape',labels.shape)
    return data, labels

In [27]:
prefixes = ['legumesA','legumesB','magasinA','legumesB','neigeA','neigeB']

In [23]:
import tensorflow.keras.backend as K

In [25]:
get_layer_output= K.function([conv_base.input], [conv_base.layers[1].output])

In [42]:
data_path='SYS809_projet2021_sequences1'
prefix = 'magasinA'
path = data_path + '/' + prefix
img_shape=[224,224,3]
X_train, y_train=load_data (path,img_shape,prefix)

train_results = []
train_classes = []
val_results = []
val_classes = []


prefix = 'magasinA'
path = data_path + '/' + prefix
img_shape=[224,224,3]
X_test, y_test=load_data (path,img_shape,prefix)


data shape (12, 224, 224, 3)
labels shape (12,)
data shape (12, 224, 224, 3)
labels shape (12,)


In [54]:
flatten = tf.keras.layers.Flatten()

In [70]:
for i in range(len(X_train)):
    output = get_layer_output(tf.expand_dims(X_train[i], 0, name=None))[0][0]
    train_results.append(output.flatten())
    train_classes.append(y_train[i])


In [78]:
train_results = np.array(train_results)

C:\Users\AR50980\AppData\Local\Temp/ipykernel_1964/3589288231.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  train_results = np.array(train_results)


In [71]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=1)
neigh.fit(train_results,train_classes)



C:\tools\Anaconda3\envs\finsession\lib\site-packages\sklearn\utils\validation.py:746: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array = np.asarray(array, order=order, dtype=dtype)


ValueError: Expected 2D array, got 1D array instead:
array=[array([[[1.8110417 , 0.07944677, 0.10624506, ..., 1.6969434 ,
          0.46754608, 0.5631769 ],
         [1.4981983 , 0.10631867, 0.        , ..., 1.9021187 ,
          0.        , 0.05495304],
         [1.4410777 , 0.10348615, 0.        , ..., 1.8879564 ,
          0.        , 0.08123726],
         ...,
         [0.9908458 , 0.20233342, 0.        , ..., 1.5985749 ,
          0.        , 0.        ],
         [0.87436426, 0.2689715 , 0.        , ..., 1.5693272 ,
          0.02153605, 0.23000413],
         [0.77039295, 0.22354442, 0.        , ..., 1.3677229 ,
          0.25610483, 0.27525938]],

        [[1.5039742 , 0.08445127, 0.21887986, ..., 1.9441853 ,
          1.2049465 , 0.9764885 ],
         [0.7518911 , 0.13482292, 0.        , ..., 2.2560067 ,
          0.44239622, 0.3875137 ],
         [0.8117318 , 0.13107586, 0.        , ..., 2.2460313 ,
          0.31542838, 0.3388683 ],
         ...,
         [0.5067159 , 0.24453875, 0.        , ..., 1.8192849 ,
          0.        , 0.        ],
         [0.4854286 , 0.337217  , 0.        , ..., 1.7373114 ,
          0.05221143, 0.16928604],
         [0.5725192 , 0.27576324, 0.        , ..., 1.4455299 ,
          0.24899441, 0.23439872]],

        [[1.512883  , 0.08317735, 0.2281923 , ..., 1.9463149 ,
          1.2407831 , 1.004477  ],
         [0.7585894 , 0.13338909, 0.        , ..., 2.2783017 ,
          0.54977846, 0.45802465],
         [0.75282043, 0.13474008, 0.        , ..., 2.3188388 ,
          0.5211506 , 0.4614008 ],
         ...,
         [0.450489  , 0.22565326, 0.        , ..., 1.9311538 ,
          0.07494095, 0.0384627 ],
         [0.43473852, 0.31158128, 0.        , ..., 1.8304212 ,
          0.02450705, 0.13554412],
         [0.5389275 , 0.25937966, 0.        , ..., 1.5098121 ,
          0.08918598, 0.13653105]],

        ...,

        [[0.3956754 , 0.17648801, 0.05001508, ..., 1.186937  ,
          0.60637975, 0.4556866 ],
         [0.67453855, 0.20358273, 0.19859989, ..., 1.2448125 ,
          0.93648565, 0.7911122 ],
         [1.1120802 , 0.19479695, 0.27189034, ..., 1.4185334 ,
          0.99562746, 0.95955276],
         ...,
         [0.9208451 , 0.21037027, 0.        , ..., 2.0933826 ,
          0.47726226, 0.40307325],
         [0.        , 0.26229396, 0.        , ..., 1.7970465 ,
          0.        , 0.        ],
         [0.        , 0.25983736, 0.        , ..., 1.5665575 ,
          0.37805897, 0.05007511]],

        [[0.90935016, 0.16684648, 0.15264957, ..., 1.2877605 ,
          0.45060667, 0.62240154],
         [1.5621579 , 0.1843683 , 0.2732839 , ..., 1.3576413 ,
          0.5959924 , 0.85511935],
         [1.6074268 , 0.18109375, 0.18867567, ..., 1.4930731 ,
          0.5029928 , 0.6933817 ],
         ...,
         [0.38790786, 0.225081  , 0.        , ..., 2.062687  ,
          0.44220823, 0.25541633],
         [0.        , 0.29877773, 0.        , ..., 1.531626  ,
          0.        , 0.        ],
         [0.        , 0.30668613, 0.04265571, ..., 1.4153777 ,
          0.76750004, 0.622861  ]],

        [[1.1063244 , 0.13464381, 0.08138904, ..., 1.283973  ,
          0.45072353, 0.483929  ],
         [1.2461727 , 0.13898796, 0.07704932, ..., 1.3417827 ,
          0.5810783 , 0.48123834],
         [0.7315944 , 0.15188013, 0.        , ..., 1.4741186 ,
          0.575518  , 0.3392745 ],
         ...,
         [0.        , 0.18786505, 0.        , ..., 1.7379297 ,
          0.7181147 , 0.19297746],
         [0.        , 0.24851117, 0.        , ..., 1.3289979 ,
          0.        , 0.        ],
         [0.69831324, 0.24982029, 0.14110783, ..., 1.2655104 ,
          0.41644865, 0.6563549 ]]], dtype=float32)
 array([[[1.1145124 , 0.16512789, 0.04442612, ..., 1.4334944 ,
          0.4985498 , 0.4397894 ],
         [1.0414685 , 0.21566284, 0.        , ..., 1.5480043 ,
          0.2535832 , 0.29475558],
         [1.1562433 , 0.21285881, 0.        , ..., 1.5691807 ,
          0.23564115, 0.31569797],
         ...,
         [0.2764778 , 0.05538215, 0.21947414, ..., 0.98116434,
          0.9898652 , 0.768026  ],
         [0.37674057, 0.        , 0.25637302, ..., 1.0418913 ,
          1.033553  , 0.8212993 ],
         [0.7689566 , 0.        , 0.3183723 , ..., 1.1814511 ,
          1.1744796 , 0.99064475]],

        [[1.2565163 , 0.17998105, 0.1838221 , ..., 1.6721071 ,
          0.77192914, 0.78687084],
         [0.6282248 , 0.2580218 , 0.        , ..., 1.7583776 ,
          0.36636615, 0.40172398],
         [0.54881513, 0.2544312 , 0.01277504, ..., 1.6951877 ,
          0.71751475, 0.5454986 ],
         ...,
         [0.78710335, 0.00490821, 0.18034664, ..., 0.77048314,
          0.5095161 , 0.49767324],
         [0.8483511 , 0.        , 0.22530644, ..., 0.88521695,
          0.53855145, 0.5608304 ],
         [1.230078  , 0.        , 0.37152332, ..., 1.0993264 ,
          1.00102   , 0.97474384]],

        [[1.4949918 , 0.14371043, 0.10460931, ..., 1.6917943 ,
          0.6554573 , 0.5957371 ],
         [0.8167726 , 0.20286888, 0.        , ..., 1.8284081 ,
          0.        , 0.06256774],
         [0.45524782, 0.19359791, 0.        , ..., 1.6993816 ,
          0.13031527, 0.23461029],
         ...,
         [0.7266901 , 0.        , 0.19510327, ..., 0.7863775 ,
          0.5808816 , 0.5394823 ],
         [0.74908596, 0.        , 0.23255391, ..., 0.9107448 ,
          0.60177904, 0.598222  ],
         [1.2202959 , 0.        , 0.37568077, ..., 1.0988472 ,
          1.0213453 , 0.9844452 ]],

        ...,

        [[0.85868317, 0.23842809, 0.21619278, ..., 1.576288  ,
          0.9859898 , 0.8943444 ],
         [0.59987974, 0.3305002 , 0.1645923 , ..., 1.712222  ,
          0.93102103, 0.8497828 ],
         [0.6197914 , 0.3347196 , 0.11603884, ..., 1.7113458 ,
          0.8931972 , 0.75068897],
         ...,
         [0.766974  , 0.        , 0.12681636, ..., 1.3086182 ,
          0.43478155, 0.45935506],
         [0.6400204 , 0.        , 0.08629882, ..., 1.2407006 ,
          0.34980476, 0.36907828],
         [0.89981645, 0.06428482, 0.18940812, ..., 1.2351022 ,
          0.6790824 , 0.67552406]],

        [[1.2347376 , 0.23499474, 0.05940402, ..., 1.4343626 ,
          0.44835705, 0.44473398],
         [1.0837492 , 0.31863537, 0.        , ..., 1.5445122 ,
          0.21376887, 0.28662962],
         [0.97315043, 0.320311  , 0.02129886, ..., 1.5928262 ,
          0.42277318, 0.42822206],
         ...,
         [0.7197853 , 0.        , 0.11153264, ..., 1.3247418 ,
          0.44991723, 0.43712324],
         [0.6316744 , 0.        , 0.08379608, ..., 1.2751373 ,
          0.3620522 , 0.36881226],
         [0.91103053, 0.        , 0.16652012, ..., 1.2571152 ,
          0.6015957 , 0.6155416 ]],

        [[0.6804938 , 0.1839459 , 0.08264008, ..., 1.4717265 ,
          0.9214431 , 0.6173022 ],
         [0.3210853 , 0.24699718, 0.        , ..., 1.5475644 ,
          0.73362076, 0.41841942],
         [0.38543162, 0.24553636, 0.        , ..., 1.5194324 ,
          0.67648405, 0.39081442],
         ...,
         [0.74318564, 0.        , 0.11430956, ..., 1.3379055 ,
          0.4853269 , 0.49378404],
         [0.73924947, 0.        , 0.09988604, ..., 1.310014  ,
          0.40939328, 0.4431091 ],
         [0.8880979 , 0.        , 0.1347979 , ..., 1.2941537 ,
          0.5332305 , 0.5660177 ]]], dtype=float32)
 array([[[0.06895661, 0.1414384 , 0.        , ..., 1.0668318 ,
          0.3982508 , 0.29622722],
         [0.29121214, 0.16102755, 0.1940271 , ..., 1.003243  ,
          0.9534358 , 0.7631331 ],
         [0.37687764, 0.15742934, 0.20610921, ..., 0.93920493,
          1.0466342 , 0.761747  ],
         ...,
         [0.        , 0.18395923, 0.34472552, ..., 0.60192955,
          1.5111089 , 1.0387785 ],
         [0.        , 0.21834894, 0.3267402 , ..., 0.6573197 ,
          1.4445533 , 1.0007937 ],
         [0.77013403, 0.18922228, 0.49479204, ..., 0.93963325,
          1.782402  , 1.4351616 ]],

        [[0.28192168, 0.15715265, 0.        , ..., 0.96037745,
          0.        , 0.06687641],
         [0.72635305, 0.1766022 , 0.12764725, ..., 0.81070256,
          0.41180712, 0.46434435],
         [0.7965642 , 0.17582858, 0.17012751, ..., 0.73948264,
          0.5893762 , 0.53237027],
         ...,
         [0.85698426, 0.190866  , 0.29123697, ..., 0.16995502,
          0.6765073 , 0.6137047 ],
         [0.8675717 , 0.22764823, 0.28552002, ..., 0.25798488,
          0.6888694 , 0.62273556],
         [1.6671364 , 0.18953724, 0.5663575 , ..., 0.69409674,
          1.4703758 , 1.3956805 ]],

        [[0.36688703, 0.15391552, 0.        , ..., 1.0105395 ,
          0.08986035, 0.15102622],
         [0.58966535, 0.17263916, 0.07123602, ..., 0.8188532 ,
          0.31512108, 0.3429997 ],
         [0.68848526, 0.17924058, 0.14343336, ..., 0.74489284,
          0.517972  , 0.48598957],
         ...,
         [0.8212329 , 0.16096967, 0.31769484, ..., 0.18590403,
          0.73230857, 0.69090813],
         [0.81184363, 0.17339872, 0.29660976, ..., 0.23891222,
          0.7414776 , 0.656814  ],
         [1.6210085 , 0.1438777 , 0.57754123, ..., 0.6865971 ,
          1.534411  , 1.4338827 ]],

        ...,

        [[1.4985309 , 0.07779674, 0.19915734, ..., 1.982501  ,
          1.211827  , 0.9534229 ],
         [0.5471158 , 0.13899192, 0.        , ..., 2.291713  ,
          0.39350712, 0.31498584],
         [0.7553537 , 0.1414476 , 0.        , ..., 2.3116107 ,
          0.6219038 , 0.55102974],
         ...,
         [0.854055  , 0.06520046, 0.06405491, ..., 1.1115917 ,
          0.4118241 , 0.38383293],
         [0.59527695, 0.11153693, 0.10214088, ..., 1.168929  ,
          0.6207793 , 0.5443731 ],
         [0.79716575, 0.10449561, 0.17172015, ..., 1.2192461 ,
          0.79440707, 0.71486056]],

        [[1.4918361 , 0.07873688, 0.19912879, ..., 1.9771304 ,
          1.2084773 , 0.9521074 ],
         [0.551213  , 0.13974223, 0.        , ..., 2.2761192 ,
          0.3721649 , 0.29956064],
         [0.7771152 , 0.14212808, 0.        , ..., 2.2999668 ,
          0.6126767 , 0.55218935],
         ...,
         [0.49611723, 0.10744503, 0.0837032 , ..., 1.1372427 ,
          0.6190039 , 0.49502894],
         [0.7409998 , 0.1302439 , 0.09824564, ..., 1.1040038 ,
          0.52540946, 0.48741445],
         [0.97281975, 0.11071924, 0.16311298, ..., 1.1828164 ,
          0.66386   , 0.6499241 ]],

        [[0.7463154 , 0.08247607, 0.08139845, ..., 1.7141998 ,
          1.3456762 , 0.740834  ],
         [0.        , 0.127131  , 0.        , ..., 1.8930542 ,
          0.8437617 , 0.21134615],
         [0.00842732, 0.12909898, 0.        , ..., 1.9122349 ,
          0.9971783 , 0.39171267],
         ...,
         [0.94378227, 0.11921281, 0.16817784, ..., 1.1783724 ,
          0.5519177 , 0.630504  ],
         [0.9295667 , 0.14040758, 0.1366577 , ..., 1.180427  ,
          0.5105975 , 0.56538534],
         [0.95452213, 0.12337981, 0.14098336, ..., 1.2378986 ,
          0.5800008 , 0.60830265]]], dtype=float32)
 array([[[0.14882618, 0.20518766, 0.13987167, ..., 1.0711901 ,
          0.71844715, 0.6413642 ],
         [0.45248505, 0.19157897, 0.27220964, ..., 0.9234741 ,
          1.1133714 , 0.8785106 ],
         [0.08544391, 0.1715789 , 0.12763807, ..., 0.8998396 ,
          0.79779077, 0.56717306],
         ...,
         [1.5540631 , 0.25951275, 0.        , ..., 1.829618  ,
          0.        , 0.1248588 ],
         [1.3934417 , 0.27001688, 0.        , ..., 1.8395728 ,
          0.        , 0.00876504],
         [0.69632584, 0.22880906, 0.        , ..., 1.5936623 ,
          0.        , 0.        ]],

        [[0.56822044, 0.22954947, 0.0663995 , ..., 0.91578877,
          0.21724632, 0.35685667],
         [0.93238664, 0.20934403, 0.14792453, ..., 0.6532378 ,
          0.47491845, 0.41288623],
         [0.34688774, 0.20389369, 0.00723165, ..., 0.63288796,
          0.17459497, 0.13435963],
         ...,
         [0.8102825 , 0.35815582, 0.        , ..., 2.1393428 ,
          0.59525716, 0.4695299 ],
         [0.5573718 , 0.3793687 , 0.        , ..., 2.1459665 ,
          0.38787144, 0.3052628 ],
         [0.        , 0.31636742, 0.        , ..., 1.7836391 ,
          0.        , 0.        ]],

        [[0.42458993, 0.22744814, 0.02503937, ..., 0.9361467 ,
          0.20657063, 0.29159898],
         [0.5186441 , 0.23496929, 0.11733617, ..., 0.6875268 ,
          0.53144175, 0.41389006],
         [0.18676627, 0.23273301, 0.04989816, ..., 0.5908082 ,
          0.37923566, 0.26751056],
         ...,
         [0.79838306, 0.3637312 , 0.        , ..., 2.1276217 ,
          0.5821678 , 0.45098287],
         [0.53821313, 0.39011368, 0.        , ..., 2.134101  ,
          0.37672392, 0.29378784],
         [0.        , 0.32561907, 0.        , ..., 1.7715347 ,
          0.        , 0.        ]],

        ...,

        [[0.72637266, 0.16078705, 0.07467259, ..., 1.2445878 ,
          0.50179464, 0.48789325],
         [0.9437368 , 0.17633651, 0.14950642, ..., 1.2829168 ,
          0.71541667, 0.661405  ],
         [0.9898685 , 0.16536033, 0.1386584 , ..., 1.3953149 ,
          0.7340105 , 0.6641781 ],
         ...,
         [1.007909  , 0.24528077, 0.29167542, ..., 1.5467993 ,
          1.4013093 , 1.1062758 ],
         [0.9204462 , 0.20570704, 0.14222734, ..., 1.773416  ,
          1.0792587 , 0.8188291 ],
         [0.22855294, 0.16143113, 0.        , ..., 1.669342  ,
          0.        , 0.        ]],

        [[0.7419363 , 0.15565583, 0.07288237, ..., 1.2560645 ,
          0.49959958, 0.48485026],
         [0.914607  , 0.17256698, 0.13322182, ..., 1.2887697 ,
          0.6720573 , 0.62488335],
         [1.0101693 , 0.16226476, 0.15803598, ..., 1.4181913 ,
          0.7917999 , 0.7174307 ],
         ...,
         [1.0032182 , 0.2826359 , 0.25124168, ..., 1.3621099 ,
          1.1396677 , 0.9444727 ],
         [1.132967  , 0.22268787, 0.2538228 , ..., 1.6226056 ,
          1.3833168 , 1.0312378 ],
         [0.11898518, 0.16301909, 0.        , ..., 1.5870445 ,
          0.1705443 , 0.        ]],

        [[0.76396215, 0.13531509, 0.07491634, ..., 1.2776098 ,
          0.50521237, 0.49283415],
         [0.8502523 , 0.14683273, 0.10590537, ..., 1.293476  ,
          0.61157537, 0.56679785],
         [0.8642409 , 0.13886096, 0.12145212, ..., 1.3772442 ,
          0.7692728 , 0.6458857 ],
         ...,
         [0.91225946, 0.23344985, 0.18702325, ..., 1.2941835 ,
          0.7837391 , 0.73967165],
         [0.98717695, 0.19552465, 0.27172846, ..., 1.5023886 ,
          1.3240819 , 1.051357  ],
         [0.13899165, 0.14475305, 0.        , ..., 1.4644005 ,
          0.63084584, 0.274884  ]]], dtype=float32)
 array([[[0.        , 0.15730557, 0.07862969, ..., 0.9254    ,
          0.7012836 , 0.52704185],
         [0.        , 0.14193524, 0.24177934, ..., 0.6542495 ,
          1.2656887 , 0.8267989 ],
         [0.        , 0.14977512, 0.2500497 , ..., 0.6959556 ,
          1.2771014 , 0.8691269 ],
         ...,
         [0.7942882 , 0.20183367, 0.28871614, ..., 1.1521305 ,
          0.826904  , 0.90384555],
         [0.8156337 , 0.20039326, 0.26554984, ..., 1.1826676 ,
          0.7858111 , 0.857545  ],
         [0.95163965, 0.16721687, 0.2613573 , ..., 1.2481359 ,
          0.8514006 , 0.8845949 ]],

        [[0.09226394, 0.19448076, 0.        , ..., 0.6747688 ,
          0.05504513, 0.18753201],
         [0.7188199 , 0.16128796, 0.19577551, ..., 0.2775824 ,
          0.5155176 , 0.45299694],
         [0.6459405 , 0.16336097, 0.20058446, ..., 0.34606862,
          0.47917703, 0.498511  ],
         ...,
         [1.4448891 , 0.21459904, 0.06857586, ..., 1.115277  ,
          0.00903428, 0.28456944],
         [1.3727319 , 0.21784002, 0.06862297, ..., 1.1545284 ,
          0.07410288, 0.30856574],
         [1.2341993 , 0.17844617, 0.08674684, ..., 1.212405  ,
          0.26152402, 0.40672404]],

        [[0.32410103, 0.20850682, 0.03039816, ..., 0.74902374,
          0.        , 0.23561743],
         [0.8571983 , 0.1820184 , 0.20071648, ..., 0.3602854 ,
          0.37006116, 0.4531837 ],
         [0.68612844, 0.17132086, 0.17844091, ..., 0.36213446,
          0.36881188, 0.44104862],
         ...,
         [0.8341773 , 0.19290188, 0.05465908, ..., 1.39344   ,
          0.45671457, 0.45326996],
         [0.8174854 , 0.19868177, 0.05588051, ..., 1.3959144 ,
          0.4793924 , 0.46031913],
         [0.68341166, 0.16829126, 0.01264695, ..., 1.3581036 ,
          0.3856823 , 0.3616014 ]],

        ...,

        [[0.63320136, 0.24391732, 0.        , ..., 0.678119  ,
          0.        , 0.        ],
         [1.5768486 , 0.2494016 , 0.22446094, ..., 0.4955691 ,
          0.24808845, 0.4674117 ],
         [1.1626728 , 0.23845395, 0.27530855, ..., 0.69121593,
          0.7642511 , 0.71935666],
         ...,
         [0.89415073, 0.10076085, 0.        , ..., 2.1105082 ,
          0.69622266, 0.5687144 ],
         [0.70274466, 0.10782719, 0.        , ..., 2.1789439 ,
          0.5120629 , 0.42703983],
         [0.        , 0.11078881, 0.        , ..., 1.8376018 ,
          0.        , 0.        ]],

        [[0.        , 0.26379886, 0.        , ..., 0.8182728 ,
          0.2232024 , 0.13244078],
         [0.31069306, 0.30909964, 0.11265236, ..., 0.53916377,
          0.71906364, 0.41931278],
         [0.31129578, 0.3144945 , 0.10704271, ..., 0.49871987,
          0.7222612 , 0.3945435 ],
         ...,
         [0.76799643, 0.10726473, 0.01640731, ..., 2.0401707 ,
          0.888     , 0.64693743],
         [0.673921  , 0.10960767, 0.        , ..., 2.1401052 ,
          0.62951374, 0.47969475],
         [0.        , 0.11119927, 0.        , ..., 1.8260713 ,
          0.        , 0.        ]],

        [[0.54653126, 0.23334792, 0.0727933 , ..., 0.97976077,
          0.        , 0.33278793],
         [1.1256557 , 0.26372778, 0.3197533 , ..., 0.8198292 ,
          0.39980423, 0.7852043 ],
         [1.1410228 , 0.25737312, 0.34934092, ..., 0.80744743,
          0.46829477, 0.84873235],
         ...,
         [0.33996892, 0.10688049, 0.01511873, ..., 1.7413754 ,
          1.157369  , 0.64189535],
         [0.11557627, 0.10691057, 0.        , ..., 1.8083096 ,
          1.0178545 , 0.45162103],
         [0.        , 0.10820763, 0.        , ..., 1.6138902 ,
          0.24907917, 0.        ]]], dtype=float32)
 array([[[0.        , 0.17771165, 0.08876885, ..., 0.89917713,
          0.59585637, 0.52355343],
         [0.        , 0.18571739, 0.34622744, ..., 0.64640146,
          1.3236098 , 1.0359707 ],
         [0.1161654 , 0.1924698 , 0.388415  , ..., 0.6950016 ,
          1.411226  , 1.1471565 ],
         ...,
         [0.7084558 , 0.16472998, 0.08767345, ..., 1.2710602 ,
          0.58083564, 0.5171466 ],
         [0.72145224, 0.16196992, 0.08597073, ..., 1.2789254 ,
          0.5716464 , 0.5123713 ],
         [0.737462  , 0.13850236, 0.08350947, ..., 1.2904809 ,
          0.56620127, 0.51382846]],

        [[0.        , 0.21446595, 0.        , ..., 0.47718656,
          0.        , 0.        ],
         [0.7949266 , 0.21094453, 0.17427295, ..., 0.10680294,
          0.52743125, 0.38210163],
         [1.2417724 , 0.20435682, 0.26827118, ..., 0.2669444 ,
          0.5751082 , 0.58779424],
         ...,
         [0.78806466, 0.20398395, 0.09275287, ..., 1.2657145 ,
          0.53850216, 0.50831175],
         [0.77499545, 0.19858341, 0.08532358, ..., 1.2735655 ,
          0.5257131 , 0.49228346],
         [0.76641107, 0.16259794, 0.08402295, ..., 1.289488  ,
          0.5406712 , 0.5052434 ]],

        [[0.        , 0.26096025, 0.        , ..., 0.45963585,
          0.03590345, 0.02354765],
         [0.32007715, 0.2598029 , 0.36545628, ..., 0.0691005 ,
          1.2539953 , 0.89617425],
         [0.68415105, 0.22347921, 0.38512823, ..., 0.21254838,
          1.4006221 , 0.9788715 ],
         ...,
         [1.1506083 , 0.2075105 , 0.1272089 , ..., 1.4417427 ,
          0.36253437, 0.5652005 ],
         [1.1455574 , 0.2007122 , 0.1167949 , ..., 1.4661094 ,
          0.31643888, 0.5441323 ],
         [0.9310736 , 0.16351554, 0.05027255, ..., 1.4098876 ,
          0.23837563, 0.40973788]],

        ...,

        [[0.00854373, 0.33178443, 0.        , ..., 0.9154769 ,
          0.24827635, 0.06224552],
         [0.        , 0.42615676, 0.        , ..., 0.63148826,
          0.5958572 , 0.15996385],
         [0.        , 0.41746697, 0.        , ..., 0.4320162 ,
          0.6718638 , 0.08556846],
         ...,
         [0.93875146, 0.13932158, 0.07010605, ..., 1.7020478 ,
          0.62185115, 0.6123508 ],
         [0.57845455, 0.14776461, 0.        , ..., 1.5601315 ,
          0.17438823, 0.16250527],
         [0.43243045, 0.15942565, 0.        , ..., 1.4891127 ,
          0.11729878, 0.19908488]],

        [[0.        , 0.318954  , 0.        , ..., 0.65225494,
          0.35059255, 0.00568789],
         [0.        , 0.38049343, 0.10965811, ..., 0.26137578,
          1.0332468 , 0.44188634],
         [0.        , 0.3722373 , 0.26523426, ..., 0.19880068,
          1.1730521 , 0.74277496],
         ...,
         [0.9769631 , 0.13934255, 0.0754895 , ..., 1.747678  ,
          0.6507501 , 0.6356673 ],
         [0.6025933 , 0.14415322, 0.        , ..., 1.6216477 ,
          0.18806255, 0.16704878],
         [0.3734083 , 0.15627712, 0.        , ..., 1.5280298 ,
          0.04069957, 0.11959237]],

        [[0.343618  , 0.24849918, 0.08895971, ..., 0.8304066 ,
          0.        , 0.3088081 ],
         [1.341924  , 0.26815563, 0.38894877, ..., 0.48840493,
          0.06434694, 0.7689447 ],
         [1.8566796 , 0.25452897, 0.43623194, ..., 0.41279364,
          0.        , 0.80150753],
         ...,
         [0.5424214 , 0.12704144, 0.01085903, ..., 1.5859513 ,
          0.8346775 , 0.5254759 ],
         [0.25515231, 0.13100809, 0.        , ..., 1.5131811 ,
          0.518165  , 0.20510066],
         [0.17512709, 0.13971087, 0.        , ..., 1.4482722 ,
          0.28791738, 0.1443634 ]]], dtype=float32)
 array([[[0.        , 0.15123276, 0.10679477, ..., 0.96806884,
          0.80126584, 0.60582983],
         [0.        , 0.13816778, 0.21737406, ..., 0.69959956,
          1.1978251 , 0.7597321 ],
         [0.        , 0.1786302 , 0.20494144, ..., 0.7636584 ,
          1.0835481 , 0.76080704],
         ...,
         [1.5865959 , 0.11181337, 0.        , ..., 1.9270948 ,
          0.        , 0.11528933],
         [1.6077023 , 0.11417788, 0.        , ..., 1.9321928 ,
          0.        , 0.11523306],
         [0.7459017 , 0.10792474, 0.        , ..., 1.6636859 ,
          0.        , 0.        ]],

        [[0.        , 0.18024296, 0.        , ..., 0.6637366 ,
          0.13268077, 0.17690828],
         [0.50873375, 0.16189167, 0.19233897, ..., 0.2883278 ,
          0.7474088 , 0.5045213 ],
         [0.3607668 , 0.19916585, 0.12364873, ..., 0.2819972 ,
          0.5469862 , 0.35032845],
         ...,
         [0.7959845 , 0.14319974, 0.        , ..., 2.291212  ,
          0.511728  , 0.45853558],
         [0.8021869 , 0.14350249, 0.        , ..., 2.299024  ,
          0.5103151 , 0.45307255],
         [0.        , 0.13259631, 0.        , ..., 1.908781  ,
          0.        , 0.        ]],

        [[0.        , 0.20353997, 0.        , ..., 0.6401945 ,
          0.        , 0.08941406],
         [0.7922734 , 0.1913957 , 0.3216091 , ..., 0.32739037,
          0.7207589 , 0.7426168 ],
         [0.7129216 , 0.20007476, 0.30279863, ..., 0.35430562,
          0.67445207, 0.70843256],
         ...,
         [0.7912257 , 0.14690186, 0.        , ..., 2.302307  ,
          0.59673727, 0.5029885 ],
         [0.7979828 , 0.14206652, 0.        , ..., 2.335526  ,
          0.51953465, 0.46750286],
         [0.        , 0.1291116 , 0.        , ..., 1.933372  ,
          0.        , 0.        ]],

        ...,

        [[0.21254778, 0.19907728, 0.        , ..., 0.79921454,
          0.02624726, 0.14875126],
         [0.8279513 , 0.20751859, 0.19605711, ..., 0.5408971 ,
          0.53840655, 0.5337595 ],
         [0.8384669 , 0.21429285, 0.2020906 , ..., 0.57767016,
          0.56810594, 0.55855966],
         ...,
         [0.7273695 , 0.3161655 , 0.03324034, ..., 1.8378408 ,
          0.6023974 , 0.5669191 ],
         [0.80599236, 0.30466563, 0.0200017 , ..., 1.8413782 ,
          0.611537  , 0.5448302 ],
         [0.25655514, 0.22802293, 0.        , ..., 1.6058211 ,
          0.        , 0.        ]],

        [[0.24406281, 0.19250318, 0.        , ..., 0.8229407 ,
          0.03699061, 0.15907678],
         [0.8340165 , 0.19811022, 0.19225308, ..., 0.5782933 ,
          0.5284602 , 0.53263944],
         [0.83871317, 0.2036482 , 0.19230112, ..., 0.60497856,
          0.5442756 , 0.5429556 ],
         ...,
         [0.902861  , 0.31908667, 0.        , ..., 1.790236  ,
          0.39147156, 0.36110395],
         [0.867653  , 0.32029647, 0.01685163, ..., 1.8706385 ,
          0.53652877, 0.5150947 ],
         [0.22842586, 0.24678361, 0.        , ..., 1.6515442 ,
          0.01876503, 0.        ]],

        [[0.7406006 , 0.15938693, 0.0557486 , ..., 1.0129473 ,
          0.        , 0.3074875 ],
         [1.3277509 , 0.15911993, 0.23310553, ..., 0.86520606,
          0.23303238, 0.6032981 ],
         [1.316153  , 0.16139102, 0.23279513, ..., 0.8812159 ,
          0.25830188, 0.61291134],
         ...,
         [0.2436395 , 0.25156423, 0.        , ..., 1.6455016 ,
          0.83762246, 0.40747586],
         [0.29759935, 0.2549115 , 0.        , ..., 1.649962  ,
          0.7478353 , 0.3511734 ],
         [0.02677041, 0.2035935 , 0.        , ..., 1.4933155 ,
          0.27877253, 0.        ]]], dtype=float32)
 array([[[1.6097945 , 0.11599854, 0.11025627, ..., 1.615782  ,
          0.48050654, 0.57004225],
         [1.4500152 , 0.14883825, 0.        , ..., 1.7989879 ,
          0.        , 0.22122401],
         [1.4325725 , 0.1437217 , 0.        , ..., 1.8041563 ,
          0.        , 0.18761426],
         ...,
         [1.7420204 , 0.09608856, 0.        , ..., 2.0605145 ,
          0.        , 0.        ],
         [1.7148285 , 0.09717438, 0.        , ..., 2.0554385 ,
          0.        , 0.        ],
         [0.7174295 , 0.09516375, 0.        , ..., 1.7304384 ,
          0.        , 0.        ]],

        [[1.3829564 , 0.12701012, 0.17313302, ..., 1.8002567 ,
          1.0115341 , 0.83240795],
         [0.83307534, 0.18476176, 0.        , ..., 2.0840492 ,
          0.5028104 , 0.45323813],
         [0.79044604, 0.18206549, 0.        , ..., 2.090045  ,
          0.4750314 , 0.42198333],
         ...,
         [0.71024966, 0.1238828 , 0.        , ..., 2.4944696 ,
          0.55739135, 0.45892248],
         [0.6762785 , 0.1248434 , 0.        , ..., 2.4833517 ,
          0.51392287, 0.42008168],
         [0.        , 0.12045379, 0.        , ..., 2.0138483 ,
          0.        , 0.        ]],

        [[1.3326998 , 0.1195252 , 0.18020798, ..., 1.8207607 ,
          1.0744275 , 0.8664222 ],
         [0.73823017, 0.18193543, 0.        , ..., 2.1084335 ,
          0.57389605, 0.48697647],
         [0.70744896, 0.18482497, 0.        , ..., 2.1063297 ,
          0.54570115, 0.45112574],
         ...,
         [0.7320519 , 0.12458976, 0.        , ..., 2.4817052 ,
          0.5631319 , 0.46974012],
         [0.7019449 , 0.12483181, 0.        , ..., 2.478589  ,
          0.5126243 , 0.43036908],
         [0.        , 0.12058343, 0.        , ..., 2.0144546 ,
          0.        , 0.        ]],

        ...,

        [[1.3593276 , 0.28182182, 0.06675714, ..., 1.3087867 ,
          0.12322551, 0.35607535],
         [1.7222253 , 0.3744109 , 0.0314155 , ..., 1.3268418 ,
          0.        , 0.21125057],
         [1.6771238 , 0.38945988, 0.        , ..., 1.3021766 ,
          0.        , 0.        ],
         ...,
         [0.88238287, 0.30772683, 0.13974318, ..., 1.065764  ,
          0.54154897, 0.5431899 ],
         [0.95854276, 0.30233952, 0.15024932, ..., 1.1173978 ,
          0.56695735, 0.57674557],
         [0.9831874 , 0.23115203, 0.14988181, ..., 1.2009    ,
          0.6206455 , 0.6104372 ]],

        [[0.97629637, 0.303559  , 0.0864504 , ..., 1.4541912 ,
          0.6917845 , 0.5305785 ],
         [0.70053196, 0.42132694, 0.03841724, ..., 1.605262  ,
          0.6834504 , 0.48536637],
         [0.4217047 , 0.42335975, 0.00821982, ..., 1.61956   ,
          0.7453771 , 0.45351562],
         ...,
         [1.1167989 , 0.30992022, 0.17292026, ..., 1.1844754 ,
          0.5332714 , 0.6156415 ],
         [1.3340592 , 0.29554158, 0.20344575, ..., 1.31642   ,
          0.5153234 , 0.6890241 ],
         [1.1123493 , 0.22393328, 0.08990741, ..., 1.3490319 ,
          0.27507117, 0.45829502]],

        [[0.59341896, 0.258587  , 0.08363485, ..., 1.4158595 ,
          0.8187277 , 0.56383044],
         [0.3665439 , 0.3527729 , 0.05409268, ..., 1.499246  ,
          0.81093955, 0.5478718 ],
         [0.37997288, 0.3408324 , 0.03744417, ..., 1.4482303 ,
          0.74345803, 0.48398393],
         ...,
         [1.042947  , 0.23056525, 0.11702324, ..., 1.2533377 ,
          0.55672044, 0.54549116],
         [1.1035485 , 0.21536466, 0.08975074, ..., 1.3462557 ,
          0.62058693, 0.5292093 ],
         [0.68603903, 0.16623543, 0.        , ..., 1.3173962 ,
          0.23871416, 0.11711985]]], dtype=float32)
 array([[[1.0364958 , 0.1467266 , 0.12844813, ..., 1.399835  ,
          0.5144773 , 0.6008669 ],
         [1.0943497 , 0.17507353, 0.1133005 , ..., 1.4567645 ,
          0.39743686, 0.5599888 ],
         [1.1408908 , 0.17636575, 0.10804673, ..., 1.4935544 ,
          0.3806172 , 0.55437505],
         ...,
         [1.5056905 , 0.10977148, 0.        , ..., 1.8764672 ,
          0.        , 0.12397012],
         [1.519408  , 0.11053202, 0.        , ..., 1.8800882 ,
          0.        , 0.12345544],
         [0.73011804, 0.10454706, 0.        , ..., 1.6326635 ,
          0.        , 0.        ]],

        [[1.4991057 , 0.1487128 , 0.14469692, ..., 1.56284   ,
          0.47190225, 0.62882674],
         [1.4084861 , 0.19415435, 0.04156913, ..., 1.7153912 ,
          0.09728685, 0.41479647],
         [1.3869939 , 0.19761033, 0.05127223, ..., 1.7568547 ,
          0.16980848, 0.45837042],
         ...,
         [0.775071  , 0.13510129, 0.        , ..., 2.2260375 ,
          0.51610756, 0.47099298],
         [0.777136  , 0.13091385, 0.        , ..., 2.2314484 ,
          0.52876204, 0.4778818 ],
         [0.        , 0.12003689, 0.        , ..., 1.8627733 ,
          0.        , 0.        ]],

        [[1.5849445 , 0.11742847, 0.14626579, ..., 1.7479196 ,
          0.7311981 , 0.71012235],
         [1.1614133 , 0.17104301, 0.        , ..., 1.9952996 ,
          0.15030596, 0.31048262],
         [1.1504991 , 0.17264158, 0.        , ..., 2.0045612 ,
          0.21476188, 0.3491199 ],
         ...,
         [0.7651986 , 0.1308147 , 0.        , ..., 2.2283928 ,
          0.49402967, 0.4315503 ],
         [0.75156903, 0.11936151, 0.        , ..., 2.232046  ,
          0.4999467 , 0.43596694],
         [0.        , 0.10744445, 0.        , ..., 1.8602607 ,
          0.        , 0.        ]],

        ...,

        [[0.6184373 , 0.16282171, 0.04927982, ..., 1.1577486 ,
          0.39149028, 0.40069014],
         [0.8675194 , 0.19087294, 0.14636524, ..., 1.1285969 ,
          0.6558739 , 0.60014904],
         [0.8555604 , 0.19885814, 0.12702668, ..., 1.1842101 ,
          0.64931977, 0.574006  ],
         ...,
         [0.6340561 , 0.09678267, 0.08390608, ..., 1.0591054 ,
          0.5847282 , 0.48719424],
         [0.6618845 , 0.09267071, 0.08168769, ..., 1.0498692 ,
          0.5593655 , 0.47426993],
         [0.9032489 , 0.09369623, 0.16981414, ..., 1.1500851 ,
          0.7614049 , 0.69204277]],

        [[0.56076574, 0.15807074, 0.02283319, ..., 1.1549295 ,
          0.34027267, 0.3389898 ],
         [0.8116348 , 0.19433646, 0.14403921, ..., 1.1396683 ,
          0.64923155, 0.60398555],
         [0.9046167 , 0.20322782, 0.16063961, ..., 1.1882545 ,
          0.737558  , 0.65074074],
         ...,
         [0.58013624, 0.13433614, 0.11455946, ..., 0.98529816,
          0.6786395 , 0.5411926 ],
         [0.59973437, 0.12775344, 0.11111201, ..., 0.99355495,
          0.6622001 , 0.53528965],
         [0.8943966 , 0.11472125, 0.20638262, ..., 1.1182988 ,
          0.8827269 , 0.7750075 ]],

        [[0.6711963 , 0.13552299, 0.03733993, ..., 1.2067666 ,
          0.31092176, 0.36568886],
         [0.92759746, 0.16295391, 0.13968953, ..., 1.2024385 ,
          0.509531  , 0.5855783 ],
         [1.0125588 , 0.16883829, 0.16288474, ..., 1.2268795 ,
          0.650676  , 0.64877725],
         ...,
         [0.99579936, 0.13510144, 0.17560172, ..., 1.0803131 ,
          0.45728412, 0.61381763],
         [0.98568106, 0.13123183, 0.1691874 , ..., 1.0893141 ,
          0.45756882, 0.6059302 ],
         [1.1407778 , 0.11670713, 0.23050715, ..., 1.1804712 ,
          0.69849706, 0.78759646]]], dtype=float32)
 array([[[0.00000000e+00, 1.84730440e-01, 1.27895921e-03, ...,
          9.35517609e-01, 3.72032404e-01, 3.00644398e-01],
         [0.00000000e+00, 2.35005945e-01, 1.80357948e-01, ...,
          6.40020907e-01, 9.56191301e-01, 6.74649239e-01],
         [0.00000000e+00, 2.53577471e-01, 3.02904248e-01, ...,
          4.92657304e-01, 1.42303109e+00, 9.56030846e-01],
         ...,
         [8.90796721e-01, 2.01949149e-01, 0.00000000e+00, ...,
          1.53612995e+00, 8.67834091e-02, 9.04991031e-02],
         [7.80780554e-01, 2.24760324e-01, 0.00000000e+00, ...,
          1.48773730e+00, 1.73595369e-01, 1.20774776e-01],
         [5.58775842e-01, 1.86929703e-01, 0.00000000e+00, ...,
          1.37627649e+00, 1.28512770e-01, 5.26288152e-02]],

        [[2.37518132e-01, 1.99540272e-01, 0.00000000e+00, ...,
          7.57996261e-01, 0.00000000e+00, 0.00000000e+00],
         [3.47621053e-01, 2.57629484e-01, 0.00000000e+00, ...,
          2.50481248e-01, 0.00000000e+00, 0.00000000e+00],
         [5.05479932e-01, 2.98234463e-01, 1.43485233e-01, ...,
          4.93288040e-02, 1.26071632e-01, 2.57331014e-01],
         ...,
         [3.87886673e-01, 2.76844770e-01, 0.00000000e+00, ...,
          1.71932721e+00, 5.52389324e-01, 4.42060947e-01],
         [4.05982941e-01, 3.15731317e-01, 4.44107950e-02, ...,
          1.66831696e+00, 6.48002386e-01, 5.59205413e-01],
         [3.39031935e-01, 2.54386842e-01, 0.00000000e+00, ...,
          1.50161242e+00, 4.62627918e-01, 3.87844861e-01]],

        [[1.16107464e-01, 1.82716191e-01, 0.00000000e+00, ...,
          8.45689058e-01, 0.00000000e+00, 2.04026997e-02],
         [0.00000000e+00, 2.40276933e-01, 0.00000000e+00, ...,
          3.13239396e-01, 0.00000000e+00, 0.00000000e+00],
         [2.89940238e-01, 2.95842201e-01, 1.13262519e-01, ...,
          1.03897452e-01, 1.38407648e-01, 2.40239546e-01],
         ...,
         [7.99435019e-01, 2.73961335e-01, 0.00000000e+00, ...,
          1.68380713e+00, 2.65844285e-01, 3.21413994e-01],
         [9.76407170e-01, 3.06543738e-01, 0.00000000e+00, ...,
          1.63628829e+00, 2.08801806e-01, 3.50656152e-01],
         [7.52593279e-01, 2.44762897e-01, 0.00000000e+00, ...,
          1.48193645e+00, 5.16539812e-03, 1.36731565e-01]],

        ...,

        [[1.16402590e+00, 4.22368467e-01, 1.68718532e-01, ...,
          1.68622994e+00, 1.08760786e+00, 8.77727985e-01],
         [6.50547802e-01, 6.12887442e-01, 0.00000000e+00, ...,
          1.90095496e+00, 7.01390386e-01, 6.00629449e-01],
         [6.83428049e-01, 6.14405990e-01, 0.00000000e+00, ...,
          1.90439808e+00, 6.84726000e-01, 5.99977195e-01],
         ...,
         [1.24433374e+00, 2.12374479e-01, 2.81044066e-01, ...,
          3.43899071e-01, 1.89510435e-01, 5.44874191e-01],
         [1.26631975e+00, 2.14314088e-01, 2.96195209e-01, ...,
          3.41625988e-01, 2.19515264e-01, 5.78105927e-01],
         [2.08861446e+00, 1.70150578e-01, 6.27170324e-01, ...,
          7.22444057e-01, 1.25036728e+00, 1.47356176e+00]],

        [[1.22172678e+00, 3.76163304e-01, 9.54781920e-02, ...,
          1.60742247e+00, 8.60524237e-01, 6.66691720e-01],
         [5.93871891e-01, 5.44216514e-01, 0.00000000e+00, ...,
          1.72667193e+00, 3.94023120e-01, 2.25089401e-01],
         [4.72081006e-01, 5.50829113e-01, 0.00000000e+00, ...,
          1.66381812e+00, 5.27741253e-01, 2.38678694e-01],
         ...,
         [1.13465250e+00, 2.13666216e-01, 9.41252708e-02, ...,
          4.96579170e-01, 4.11599874e-03, 2.01486051e-01],
         [1.09810972e+00, 2.29059428e-01, 1.03886724e-01, ...,
          4.61654961e-01, 7.18972683e-02, 2.23827362e-01],
         [1.73419094e+00, 1.84246749e-01, 4.06344742e-01, ...,
          7.61493325e-01, 9.74022269e-01, 1.01968229e+00]],

        [[6.64887667e-01, 2.61415005e-01, 6.58906102e-02, ...,
          1.51486540e+00, 1.06016159e+00, 6.40651882e-01],
         [0.00000000e+00, 3.72503012e-01, 0.00000000e+00, ...,
          1.59582806e+00, 7.80804515e-01, 3.46925378e-01],
         [0.00000000e+00, 3.84420633e-01, 0.00000000e+00, ...,
          1.57760954e+00, 9.53778744e-01, 5.58950543e-01],
         ...,
         [1.06858611e+00, 1.91412449e-01, 1.70648754e-01, ...,
          9.28590059e-01, 2.02585310e-01, 4.94825423e-01],
         [1.09298038e+00, 2.11800799e-01, 2.20385537e-01, ...,
          9.22810435e-01, 2.82597244e-01, 6.06588542e-01],
         [1.52952766e+00, 1.75605461e-01, 3.98288339e-01, ...,
          1.06611490e+00, 8.66796136e-01, 1.08061385e+00]]], dtype=float32)
 array([[[0.        , 0.23775885, 0.04061324, ..., 0.89407265,
          0.6035702 , 0.41983676],
         [0.        , 0.26567033, 0.27207845, ..., 0.6677981 ,
          1.3225759 , 0.8953899 ],
         [0.        , 0.2666312 , 0.24456067, ..., 0.641852  ,
          1.2667841 , 0.82926595],
         ...,
         [1.4739941 , 0.23110232, 0.2622649 , ..., 1.310905  ,
          1.1391182 , 0.8612594 ],
         [0.5698044 , 0.25206584, 0.        , ..., 1.4447842 ,
          0.        , 0.        ],
         [0.48032412, 0.24190214, 0.        , ..., 1.40444   ,
          0.18471038, 0.21760637]],

        [[0.0471586 , 0.2884372 , 0.        , ..., 0.66097707,
          0.        , 0.        ],
         [0.77776206, 0.32598817, 0.22350603, ..., 0.33829832,
          0.49271315, 0.51994616],
         [0.6962484 , 0.3251713 , 0.19715336, ..., 0.27138233,
          0.4723685 , 0.44759688],
         ...,
         [1.6272204 , 0.3000604 , 0.45052433, ..., 1.4182339 ,
          1.5920718 , 1.3136023 ],
         [0.        , 0.33011803, 0.        , ..., 1.4628023 ,
          0.13015822, 0.        ],
         [0.17096823, 0.310908  , 0.        , ..., 1.4454696 ,
          0.34332758, 0.332592  ]],

        [[0.21080619, 0.2708054 , 0.        , ..., 0.7378297 ,
          0.        , 0.        ],
         [0.7270563 , 0.3348432 , 0.15559465, ..., 0.4506141 ,
          0.20348972, 0.38061613],
         [0.7084781 , 0.32866883, 0.1999316 , ..., 0.26444876,
          0.5011352 , 0.45225418],
         ...,
         [1.599415  , 0.31930104, 0.3655088 , ..., 1.3372933 ,
          1.3011909 , 1.0855474 ],
         [0.18264353, 0.35028458, 0.        , ..., 1.3861395 ,
          0.14082217, 0.        ],
         [0.39669392, 0.3256303 , 0.0029776 , ..., 1.4174054 ,
          0.25506058, 0.35914373]],

        ...,

        [[0.7455448 , 0.31327355, 0.        , ..., 1.5807511 ,
          0.56647086, 0.31425786],
         [0.03342265, 0.5835477 , 0.        , ..., 1.5821017 ,
          0.        , 0.        ],
         [0.49000382, 0.71549696, 0.        , ..., 1.2379694 ,
          0.13325894, 0.13976508],
         ...,
         [0.53226143, 0.13712722, 0.        , ..., 2.41376   ,
          0.2982315 , 0.23650753],
         [0.7080788 , 0.15130101, 0.        , ..., 2.413577  ,
          0.5106104 , 0.47695053],
         [0.        , 0.12857759, 0.        , ..., 1.9227915 ,
          0.        , 0.        ]],

        [[0.7988748 , 0.31068587, 0.03218995, ..., 1.587534  ,
          0.66773325, 0.4440644 ],
         [0.1268965 , 0.5642901 , 0.        , ..., 1.6017374 ,
          0.03279093, 0.01237357],
         [0.37842938, 0.69920397, 0.        , ..., 1.2814516 ,
          0.1445975 , 0.12169635],
         ...,
         [0.50868297, 0.13718703, 0.        , ..., 2.4152427 ,
          0.29190964, 0.21957952],
         [0.6987369 , 0.15120852, 0.        , ..., 2.4127324 ,
          0.5162962 , 0.4717715 ],
         [0.        , 0.12796319, 0.        , ..., 1.9246398 ,
          0.        , 0.        ]],

        [[0.56953466, 0.23750615, 0.00752424, ..., 1.4570754 ,
          0.76766753, 0.4185119 ],
         [0.09293354, 0.406024  , 0.        , ..., 1.4682767 ,
          0.33246017, 0.11024401],
         [0.3980625 , 0.49728104, 0.        , ..., 1.2802091 ,
          0.27289885, 0.19664976],
         ...,
         [0.        , 0.12669797, 0.        , ..., 1.9848803 ,
          0.8699125 , 0.1406998 ],
         [0.        , 0.13611263, 0.        , ..., 1.985126  ,
          1.0007764 , 0.32868886],
         [0.        , 0.12020914, 0.        , ..., 1.6735911 ,
          0.1912094 , 0.        ]]], dtype=float32)
 array([[[0.732353  , 0.31473666, 0.08664333, ..., 1.294477  ,
          0.48905426, 0.4652512 ],
         [0.84586304, 0.40489018, 0.12971176, ..., 1.32758   ,
          0.6013361 , 0.56369734],
         [0.8439032 , 0.37006846, 0.08830827, ..., 1.3220015 ,
          0.5907863 , 0.47589877],
         ...,
         [0.37069488, 0.20967077, 0.16738118, ..., 1.0048823 ,
          0.8908347 , 0.672691  ],
         [0.25116512, 0.20371076, 0.13476987, ..., 0.98210096,
          0.81874466, 0.599389  ],
         [0.70881754, 0.17047769, 0.2883483 , ..., 1.1174086 ,
          1.1742761 , 0.9843524 ]],

        [[0.9548749 , 0.399882  , 0.09603944, ..., 1.3459616 ,
          0.4269515 , 0.45243853],
         [0.8798049 , 0.54103136, 0.09502186, ..., 1.3754649 ,
          0.39078444, 0.43355188],
         [0.73356104, 0.5224097 , 0.12727621, ..., 1.3884335 ,
          0.6128737 , 0.5481751 ],
         ...,
         [0.7738969 , 0.254388  , 0.13548145, ..., 0.845783  ,
          0.48678067, 0.4675877 ],
         [0.5803933 , 0.24379963, 0.0790887 , ..., 0.7911734 ,
          0.36896226, 0.33995086],
         [1.1530573 , 0.19476259, 0.3243053 , ..., 0.9803684 ,
          1.0106139 , 0.96352035]],

        [[0.844919  , 0.3746293 , 0.0863466 , ..., 1.3618765 ,
          0.6311246 , 0.48684904],
         [0.77402997, 0.5181749 , 0.03343818, ..., 1.3987961 ,
          0.38434327, 0.3268184 ],
         [0.84747404, 0.53002137, 0.0509439 , ..., 1.4001637 ,
          0.28670567, 0.34229326],
         ...,
         [0.7333434 , 0.25652444, 0.11209802, ..., 0.8716326 ,
          0.43171632, 0.42067528],
         [0.44525173, 0.2416277 , 0.04281352, ..., 0.7695846 ,
          0.3075965 , 0.26419142],
         [1.1031346 , 0.19260797, 0.34056535, ..., 0.9586593 ,
          1.0862454 , 1.0124823 ]],

        ...,

        [[1.4394834 , 0.0543967 , 0.1906695 , ..., 1.9250585 ,
          1.1717134 , 0.9300537 ],
         [0.7080258 , 0.09655129, 0.        , ..., 2.2618918 ,
          0.5427507 , 0.4607096 ],
         [0.70380026, 0.09847344, 0.        , ..., 2.2530036 ,
          0.5339498 , 0.4512847 ],
         ...,
         [0.71352106, 0.19358218, 0.        , ..., 2.4028141 ,
          0.5360467 , 0.4423401 ],
         [0.69788677, 0.20105764, 0.        , ..., 2.3858078 ,
          0.49840766, 0.4098924 ],
         [0.        , 0.17404056, 0.        , ..., 1.9546518 ,
          0.        , 0.        ]],

        [[1.4309986 , 0.05870705, 0.1943656 , ..., 1.9188002 ,
          1.1754389 , 0.93876034],
         [0.7212457 , 0.09967722, 0.        , ..., 2.2510793 ,
          0.5542711 , 0.47356212],
         [0.70203197, 0.09986632, 0.        , ..., 2.2401085 ,
          0.5193057 , 0.439243  ],
         ...,
         [0.7288379 , 0.19908844, 0.        , ..., 2.4046123 ,
          0.5503702 , 0.4654065 ],
         [0.7201911 , 0.20562187, 0.        , ..., 2.3947725 ,
          0.5202515 , 0.43818173],
         [0.        , 0.17747058, 0.        , ..., 1.9623052 ,
          0.        , 0.        ]],

        [[0.7608759 , 0.07077663, 0.08381536, ..., 1.6751677 ,
          1.2780468 , 0.73201954],
         [0.        , 0.10064496, 0.        , ..., 1.8781495 ,
          0.9544238 , 0.34634405],
         [0.        , 0.09979961, 0.        , ..., 1.8729975 ,
          0.9232681 , 0.31548735],
         ...,
         [0.        , 0.17019188, 0.        , ..., 1.9696397 ,
          1.0111133 , 0.30329126],
         [0.        , 0.17438625, 0.        , ..., 1.9660343 ,
          0.9951935 , 0.28536916],
         [0.        , 0.15525168, 0.        , ..., 1.6937175 ,
          0.13027099, 0.        ]]], dtype=float32)
 <tf.Tensor: shape=(224, 14336), dtype=float32, numpy=
 array([[1.8110417 , 0.07944677, 0.10624506, ..., 1.3677229 , 0.25610483,
         0.27525938],
        [1.5039742 , 0.08445127, 0.21887986, ..., 1.4455299 , 0.24899441,
         0.23439872],
        [1.512883  , 0.08317735, 0.2281923 , ..., 1.5098121 , 0.08918598,
         0.13653105],
        ...,
        [0.3956754 , 0.17648801, 0.05001508, ..., 1.5665575 , 0.37805897,
         0.05007511],
        [0.90935016, 0.16684648, 0.15264957, ..., 1.4153777 , 0.76750004,
         0.622861  ],
        [1.1063244 , 0.13464381, 0.08138904, ..., 1.2655104 , 0.41644865,
         0.6563549 ]], dtype=float32)>
 <tf.Tensor: shape=(224, 14336), dtype=float32, numpy=
 array([[1.1145124 , 0.16512789, 0.04442612, ..., 1.1814511 , 1.1744796 ,
         0.99064475],
        [1.2565163 , 0.17998105, 0.1838221 , ..., 1.0993264 , 1.00102   ,
         0.97474384],
        [1.4949918 , 0.14371043, 0.10460931, ..., 1.0988472 , 1.0213453 ,
         0.9844452 ],
        ...,
        [0.85868317, 0.23842809, 0.21619278, ..., 1.2351022 , 0.6790824 ,
         0.67552406],
        [1.2347376 , 0.23499474, 0.05940402, ..., 1.2571152 , 0.6015957 ,
         0.6155416 ],
        [0.6804938 , 0.1839459 , 0.08264008, ..., 1.2941537 , 0.5332305 ,
         0.5660177 ]], dtype=float32)>
 <tf.Tensor: shape=(224, 14336), dtype=float32, numpy=
 array([[0.06895661, 0.1414384 , 0.        , ..., 0.93963325, 1.782402  ,
         1.4351616 ],
        [0.28192168, 0.15715265, 0.        , ..., 0.69409674, 1.4703758 ,
         1.3956805 ],
        [0.36688703, 0.15391552, 0.        , ..., 0.6865971 , 1.534411  ,
         1.4338827 ],
        ...,
        [1.4985309 , 0.07779674, 0.19915734, ..., 1.2192461 , 0.79440707,
         0.71486056],
        [1.4918361 , 0.07873688, 0.19912879, ..., 1.1828164 , 0.66386   ,
         0.6499241 ],
        [0.7463154 , 0.08247607, 0.08139845, ..., 1.2378986 , 0.5800008 ,
         0.60830265]], dtype=float32)>
 <tf.Tensor: shape=(224, 14336), dtype=float32, numpy=
 array([[0.14882618, 0.20518766, 0.13987167, ..., 1.5936623 , 0.        ,
         0.        ],
        [0.56822044, 0.22954947, 0.0663995 , ..., 1.7836391 , 0.        ,
         0.        ],
        [0.42458993, 0.22744814, 0.02503937, ..., 1.7715347 , 0.        ,
         0.        ],
        ...,
        [0.72637266, 0.16078705, 0.07467259, ..., 1.669342  , 0.        ,
         0.        ],
        [0.7419363 , 0.15565583, 0.07288237, ..., 1.5870445 , 0.1705443 ,
         0.        ],
        [0.76396215, 0.13531509, 0.07491634, ..., 1.4644005 , 0.63084584,
         0.274884  ]], dtype=float32)>
 <tf.Tensor: shape=(224, 14336), dtype=float32, numpy=
 array([[0.        , 0.15730557, 0.07862969, ..., 1.2481359 , 0.8514006 ,
         0.8845949 ],
        [0.09226394, 0.19448076, 0.        , ..., 1.212405  , 0.26152402,
         0.40672404],
        [0.32410103, 0.20850682, 0.03039816, ..., 1.3581036 , 0.3856823 ,
         0.3616014 ],
        ...,
        [0.63320136, 0.24391732, 0.        , ..., 1.8376018 , 0.        ,
         0.        ],
        [0.        , 0.26379886, 0.        , ..., 1.8260713 , 0.        ,
         0.        ],
        [0.54653126, 0.23334792, 0.0727933 , ..., 1.6138902 , 0.24907917,
         0.        ]], dtype=float32)>
 <tf.Tensor: shape=(224, 14336), dtype=float32, numpy=
 array([[0.        , 0.17771165, 0.08876885, ..., 1.2904809 , 0.56620127,
         0.51382846],
        [0.        , 0.21446595, 0.        , ..., 1.289488  , 0.5406712 ,
         0.5052434 ],
        [0.        , 0.26096025, 0.        , ..., 1.4098876 , 0.23837563,
         0.40973788],
        ...,
        [0.00854373, 0.33178443, 0.        , ..., 1.4891127 , 0.11729878,
         0.19908488],
        [0.        , 0.318954  , 0.        , ..., 1.5280298 , 0.04069957,
         0.11959237],
        [0.343618  , 0.24849918, 0.08895971, ..., 1.4482722 , 0.28791738,
         0.1443634 ]], dtype=float32)>
 <tf.Tensor: shape=(224, 14336), dtype=float32, numpy=
 array([[0.        , 0.15123276, 0.10679477, ..., 1.6636859 , 0.        ,
         0.        ],
        [0.        , 0.18024296, 0.        , ..., 1.908781  , 0.        ,
         0.        ],
        [0.        , 0.20353997, 0.        , ..., 1.933372  , 0.        ,
         0.        ],
        ...,
        [0.21254778, 0.19907728, 0.        , ..., 1.6058211 , 0.        ,
         0.        ],
        [0.24406281, 0.19250318, 0.        , ..., 1.6515442 , 0.01876503,
         0.        ],
        [0.7406006 , 0.15938693, 0.0557486 , ..., 1.4933155 , 0.27877253,
         0.        ]], dtype=float32)>
 <tf.Tensor: shape=(224, 14336), dtype=float32, numpy=
 array([[1.6097945 , 0.11599854, 0.11025627, ..., 1.7304384 , 0.        ,
         0.        ],
        [1.3829564 , 0.12701012, 0.17313302, ..., 2.0138483 , 0.        ,
         0.        ],
        [1.3326998 , 0.1195252 , 0.18020798, ..., 2.0144546 , 0.        ,
         0.        ],
        ...,
        [1.3593276 , 0.28182182, 0.06675714, ..., 1.2009    , 0.6206455 ,
         0.6104372 ],
        [0.97629637, 0.303559  , 0.0864504 , ..., 1.3490319 , 0.27507117,
         0.45829502],
        [0.59341896, 0.258587  , 0.08363485, ..., 1.3173962 , 0.23871416,
         0.11711985]], dtype=float32)>
 <tf.Tensor: shape=(224, 14336), dtype=float32, numpy=
 array([[1.0364958 , 0.1467266 , 0.12844813, ..., 1.6326635 , 0.        ,
         0.        ],
        [1.4991057 , 0.1487128 , 0.14469692, ..., 1.8627733 , 0.        ,
         0.        ],
        [1.5849445 , 0.11742847, 0.14626579, ..., 1.8602607 , 0.        ,
         0.        ],
        ...,
        [0.6184373 , 0.16282171, 0.04927982, ..., 1.1500851 , 0.7614049 ,
         0.69204277],
        [0.56076574, 0.15807074, 0.02283319, ..., 1.1182988 , 0.8827269 ,
         0.7750075 ],
        [0.6711963 , 0.13552299, 0.03733993, ..., 1.1804712 , 0.69849706,
         0.78759646]], dtype=float32)>
 <tf.Tensor: shape=(224, 14336), dtype=float32, numpy=
 array([[0.00000000e+00, 1.84730440e-01, 1.27895921e-03, ...,
         1.37627649e+00, 1.28512770e-01, 5.26288152e-02],
        [2.37518132e-01, 1.99540272e-01, 0.00000000e+00, ...,
         1.50161242e+00, 4.62627918e-01, 3.87844861e-01],
        [1.16107464e-01, 1.82716191e-01, 0.00000000e+00, ...,
         1.48193645e+00, 5.16539812e-03, 1.36731565e-01],
        ...,
        [1.16402590e+00, 4.22368467e-01, 1.68718532e-01, ...,
         7.22444057e-01, 1.25036728e+00, 1.47356176e+00],
        [1.22172678e+00, 3.76163304e-01, 9.54781920e-02, ...,
         7.61493325e-01, 9.74022269e-01, 1.01968229e+00],
        [6.64887667e-01, 2.61415005e-01, 6.58906102e-02, ...,
         1.06611490e+00, 8.66796136e-01, 1.08061385e+00]], dtype=float32)>
 <tf.Tensor: shape=(224, 14336), dtype=float32, numpy=
 array([[0.        , 0.23775885, 0.04061324, ..., 1.40444   , 0.18471038,
         0.21760637],
        [0.0471586 , 0.2884372 , 0.        , ..., 1.4454696 , 0.34332758,
         0.332592  ],
        [0.21080619, 0.2708054 , 0.        , ..., 1.4174054 , 0.25506058,
         0.35914373],
        ...,
        [0.7455448 , 0.31327355, 0.        , ..., 1.9227915 , 0.        ,
         0.        ],
        [0.7988748 , 0.31068587, 0.03218995, ..., 1.9246398 , 0.        ,
         0.        ],
        [0.56953466, 0.23750615, 0.00752424, ..., 1.6735911 , 0.1912094 ,
         0.        ]], dtype=float32)>
 <tf.Tensor: shape=(224, 14336), dtype=float32, numpy=
 array([[0.732353  , 0.31473666, 0.08664333, ..., 1.1174086 , 1.1742761 ,
         0.9843524 ],
        [0.9548749 , 0.399882  , 0.09603944, ..., 0.9803684 , 1.0106139 ,
         0.96352035],
        [0.844919  , 0.3746293 , 0.0863466 , ..., 0.9586593 , 1.0862454 ,
         1.0124823 ],
        ...,
        [1.4394834 , 0.0543967 , 0.1906695 , ..., 1.9546518 , 0.        ,
         0.        ],
        [1.4309986 , 0.05870705, 0.1943656 , ..., 1.9623052 , 0.        ,
         0.        ],
        [0.7608759 , 0.07077663, 0.08381536, ..., 1.6937175 , 0.13027099,
         0.        ]], dtype=float32)>
 array([1.8110417 , 0.07944677, 0.10624506, ..., 1.2655104 , 0.41644865,
        0.6563549 ], dtype=float32)
 array([1.1145124 , 0.16512789, 0.04442612, ..., 1.2941537 , 0.5332305 ,
        0.5660177 ], dtype=float32)
 array([0.06895661, 0.1414384 , 0.        , ..., 1.2378986 , 0.5800008 ,
        0.60830265], dtype=float32)
 array([0.14882618, 0.20518766, 0.13987167, ..., 1.4644005 , 0.63084584,
        0.274884  ], dtype=float32)
 array([0.        , 0.15730557, 0.07862969, ..., 1.6138902 , 0.24907917,
        0.        ], dtype=float32)
 array([0.        , 0.17771165, 0.08876885, ..., 1.4482722 , 0.28791738,
        0.1443634 ], dtype=float32)
 array([0.        , 0.15123276, 0.10679477, ..., 1.4933155 , 0.27877253,
        0.        ], dtype=float32)
 array([1.6097945 , 0.11599854, 0.11025627, ..., 1.3173962 , 0.23871416,
        0.11711985], dtype=float32)
 array([1.0364958 , 0.1467266 , 0.12844813, ..., 1.1804712 , 0.69849706,
        0.78759646], dtype=float32)
 array([0.        , 0.18473044, 0.00127896, ..., 1.0661149 , 0.86679614,
        1.0806139 ], dtype=float32)
 array([0.        , 0.23775885, 0.04061324, ..., 1.6735911 , 0.1912094 ,
        0.        ], dtype=float32)
 array([0.732353  , 0.31473666, 0.08664333, ..., 1.6937175 , 0.13027099,
        0.        ], dtype=float32)                                     ].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.